x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: dockerfile.airflow
  env_file:
    - .env
  volumes:
    - ./plugins:/opt/airflow/plugins
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - /home/ompathare/extracted_data:/opt/airflow/extracted_data
    - /home/ompathare/transformed_data:/opt/airflow/transformed_data
  command: >
    bash -c "
    mkdir -p /opt/airflow/data &&
    chmod -R 775 /opt/airflow/data &&
    exec \$0 \$@"
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  networks:
    - containers_network

services:
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    image: airflow-init
    env_file: .env
    entrypoint: ["bash", "-c"]
    command: >
      airflow db init &&
      airflow users create --username ${AIRFLOW_ADMIN_USERNAME} --firstname ${AIRFLOW_ADMIN_FIRSTNAME} --lastname ${AIRFLOW_ADMIN_LASTNAME} --role Admin --email ${AIRFLOW_ADMIN_EMAIL} --password ${AIRFLOW_ADMIN_PASSWORD}
    networks:
      - containers_network
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"

  webserver:
    <<: *airflow-common
    command: bash -c "sleep 20 && airflow webserver"
    container_name: airflow-webserver
    image: airflow-webserver
    restart: on-failure
    ports:
      - "8082:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username ${AIRFLOW_USER_USERNAME} --firstname ${AIRFLOW_ADMIN_FIRSTNAME} --lastname ${AIRFLOW_ADMIN_LASTNAME} --role Admin --email ${AIRFLOW_ADMIN_EMAIL} --password ${AIRFLOW_USER_PASSWORD} &&
      airflow scheduler"
    container_name: airflow-scheduler
    image: airflow-scheduler
    restart: on-failure
    networks:
      - containers_network

networks:
  containers_network:
    external: true
